/* How much was each product category purchased?*/
SELECT product_category, count(product_category)
FROM sales
GROUP BY product_category
ORDER BY product_category DESC;

/* What is the amount of revenue generated by each product category?*/
SELECT product_category, sum(total_amount)
FROM sales
GROUP BY product_category;

/*Find total quantity sold per category.*/
SELECT product_category, sum(quantity)
FROM sales
GROUP BY product_category;

/*Which product category generates highest revenue?*/
SELECT product_category, round(sum(total_amount),2) as revenue
FROM sales
GROUP BY product_category
ORDER BY revenue DESC
LIMIT 1;

/*Which category sells most units but earns less revenue?*/
SELECT product_category, sum(quantity),
        round(sum(total_amount),2) as revenue
FROM customers as  c
JOIN sales as s ON c.transaction_id = s.transaction_id
GROUP BY product_category
ORDER BY revenue asc
LIMIT 1;

/*Average order value per category*/
SELECT product_category,
       ROUND(AVG(total_amount),2) AS avg_order_value
FROM sales
GROUP BY product_category;